# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2e9597fbb49046d2f6c95b9a89e4d402"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "Gst Virtue"
handle = "gst-virtue-1"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
