# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0b46e223749df9a2c17fc183b9175f99"
application_url = "https://collectables-record-representations-shell.trycloudflare.com"
embedded = true
name = "Gst Virtue"
handle = "gst-virtue-2"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_customers,read_locations"

[auth]
redirect_urls = [
  "https://collectables-record-representations-shell.trycloudflare.com/auth/callback",
  "https://collectables-record-representations-shell.trycloudflare.com/auth/shopify/callback",
  "https://collectables-record-representations-shell.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "gst-virtue-paras.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
