const mongoose = require('mongoose');

const CustomizeLabelSchema = new mongoose.Schema({
    storeName: { type: String, required: true, unique: true },
    customize_store_labels: {
        tax_invoice: String,
        export_invoice: Boolean,
        gstin: String,
        is_gstin: Boolean,
        iec_code: String,
        is_iec_code: Boolean,
        cin: String,
        is_cin: Boolean,
        pan_no: String,
        is_pan_no: Boolean,
        fssai_lic_no: String,
        is_fssai_lic_no: Boolean,
        invoice_no: String,
        is_invoice_no: Boolean,
        order_no: String,
        is_order_no: Boolean,
        invoice_date: String,
        is_invoice_date: Boolean,
        order_date: String,
        is_order_date: Boolean,
        transport_mode: String,
        is_transport_mode: Boolean,
        date_of_supply: String,
        is_date_of_supply: Boolean,
        place_of_supply: String,
        is_place_of_supply: Boolean,
        original: String,
    },
    store_information: {
        company_legal_name: String,
        branch_name: String,
        shop_domain: String,
        is_shop_domain: Boolean,
        store_address: String,
        contact_person: String,
        store_phone: String,
        store_email: String,
        terms_and_conditions: String,
    },
    billing_shipping_labels: {
        bill_to_party: String,
        ship_to_party: String,
        billing_phone: String,
        shipping_phone: String,
        billing_gstin: String,
        shipping_gstin: String,
        hide_show_phone: Boolean,
        hide_show_gstin: Boolean,
        hide_show_customer_email: Boolean,
        hide_show_shipping_section: Boolean,
    },
    product_items_labels: {
        item_sku: String,
        hide_show_product_title: Boolean,
        hide_show_product_sku: Boolean,
        hide_show_product_hsn: Boolean,
        hide_show_product_discount: Boolean,
        qty: String,
        rate_per_item: String,
        discount_item: String,
        texable_item: String,
        hsn: String,
        gst: String,
        cgst_igst: String,
        igst: String,
        cgst: String,
        sgst: String,
        cess: String,
        total: String,
    },
    others_labels: {
        payment_mode: String,
        is_payment_mode: Boolean,
        order_note: String,
        is_order_note: Boolean,
        term_and_conditions: String,
        is_term_and_conditions: Boolean,
        total_invoice_amount_in_words: String,
        is_total_invoice_amount_in_words: Boolean,
        e_and_o_e: String,
        this_is_a_computer_generated_invoice_and_does_not_require_a_signature: String,
        hide_show_financial_status: Boolean,
        hide_show_qr_code_image: Boolean,
    },
    footer_labels: {
        thank_you_for_your_business: String,
        is_thank_you_for_your_business: Boolean,
        hide_show_generated_from: Boolean,
        hide_show_page_no: Boolean,
    }
});

module.exports = mongoose.model('CustomizeLabel', CustomizeLabelSchema);