const mongoose = require('mongoose');

const ProductSchema = new mongoose.Schema({
    id: { type: String, required: true },
    shopify_id: { type: String, required: true, unique: true },
    store_name: {type: String},
    title: { type: String, required: true },
    body_html: { type: String },
    vendor: { type: String },
    product_type: { type: String },
    created_at: { type: Date },
    handle: { type: String, required: true, unique: true },
    updated_at: { type: Date },
    published_at: { type: Date },
    gst: { type: String },
    hsn: { type: String }, // this is correct hsn schema
    cess: { type: Number },
    miniAmount: { type: Number },
    minGst: { type: Number },
    Amount: { type: Number },
    template_suffix: { type: String },
    published_scope: { type: String },
    tags: { type: String },
    status: { type: String },
    admin_graphql_api_id: { type: String },
    price: { type: String },
    variants: [{
        id: { type: String, required: true },
        product_id: { type: String },
        title: { type: String },
        price: { type: String },
        position: { type: Number },
        inventory_policy: { type: String },
        compare_at_price: { type: String },
        option1: { type: String },
        option2: { type: String },
        option3: { type: String },
        created_at: { type: Date },
        updated_at: { type: Date },
        taxable: { type: Boolean },
        barcode: { type: String },
        fulfillment_service: { type: String },
        grams: { type: Number },
        inventory_management: { type: String },
        requires_shipping: { type: Boolean },
        sku: { type: String },
        weight: { type: Number },
        weight_unit: { type: String },
        inventory_item_id: { type: Number },
        inventory_quantity: { type: Number },
        old_inventory_quantity: { type: Number },
        admin_graphql_api_id: { type: String },
        image_id: { type: Number },
    }],
    options: [{
        id: { type: String },
        product_id: { type: String },
        name: { type: String },
        position: { type: Number },
        values: [String],
    }],
    images: [{
        id: { type: String },
        alt: { type: String },
        position: { type: Number },
        product_id: { type: String },
        created_at: { type: Date },
        updated_at: { type: Date },
        admin_graphql_api_id: { type: String },
        width: { type: Number },
        height: { type: Number },
        src: { type: String },
        variant_ids: [String]
    }],
    image: {
        id: { type: String, required: true },
        alt: { type: String },
        position: { type: Number },
        product_id: { type: String },
        created_at: { type: Date },
        updated_at: { type: Date },
        admin_graphql_api_id: { type: String },
        width: { type: Number },
        height: { type: Number },
        src: { type: String },
        variant_ids: [String]
    }
}, { timestamps: true });  // Automatically include createdAt/updatedAt

const Product = mongoose.model('Product', ProductSchema);

module.exports = Product;